### ISSUE TITLE
Version 2019062100 not on github

### ISSUE THREAD

**Issue by jacac** [jmvedrine/moodle-qtype_ddmatch#14]
It looks like someone forgot to push to GitHub the latest version. Moodle reports version 2019062100 is available but GitHub shows only version 2019040400.

**Comment by jmvedrine** [comment]
Hello,
I am now retired and I stopped all Moodle related activities.
This repository is here just for history and this work is not maintained any more.
Feel free to fork it and modify it to suit your needs or improve compatibility with recent Moodle versions.
According to the Moodle Plugins Directory there is a new maintainer for this plugin, but I have not managed to get in contact with them and they don't seem to have a Github repository of their version wich is very sad. You can try to contact them. Best regards.
