### ISSUE TITLE
qtype_ddmatch version 1.6 on Moodle 3.5 does not work (Build 2019062100)

### ISSUE THREAD

**Issue by will-bulluck** [jmvedrine/moodle-qtype_ddmatch#15]
Hello,

Using qtype_ddmatch version 1.6 Drag and drop matching question for Moodle 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.6, 3.7 Build 2019062100 on a Moodle 3.5 site breaks the question where you cannot drag and drop the answers. Upon inspection in the browser console, this shows up.

> Uncaught TypeError: Cannot read property 'all' of null
>     at DDMATCH.initializer (yui_combo.php?m/1568213219/qtype_ddmatch/dragdrop/dragdrop-debug.js:36)
>     at DDMATCH._initHierarchy (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:968)
>     at DDMATCH._baseInit (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:946)
>     at DDMATCH.init (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:983)
>     at DDMATCH._initBase (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:946)
>     at DDMATCH.BaseCore (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:942)
>     at DDMATCH.Base (yui_combo.php?rollup/3.17.2/yui-moodlesimple.js:986)
>     at new DDMATCH (yui_combo.php?m/1568213219/qtype_ddmatch/dragdrop/dragdrop-debug.js:6)
>     at Object.M.qtype.ddmatch.init_dragdrop (yui_combo.php?m/1568213219/qtype_ddmatch/dragdrop/dragdrop-debug.js:156)
>     at attempt.php?attempt=73&cmid=556:586

Thanks

**Comment by jmvedrine** [comment]
Hello,
I am now retired and I stopped all Moodle related activities.
This repository is here just for history and this work is not maintained any more.
Feel free to fork it and modify it to suit your needs or improve compatibility with recent Moodle versions.
According to the Moodle Plugins Directory there is a new maintainer for this plugin, but I have not managed to get in contact with them and they don't seem to have a Github repository of their version wich is very sad. You can try to contact them. Best regards.
