### ISSUE TITLE
install.xml small bug

### ISSUE THREAD

**Issue by tomhash2** [jmvedrine/moodle-qtype_ddmatch#6]
I have found that in install.xml field with name "answertext" is varchar(255) but should be text.

There is code which converts this field but only in case of upgrade.

When you have fresh install and try to move some courses from another site you might end up witch SQL error.

**Comment by andrewhancox** [comment]
This is fixed by me pull request https://github.com/jmvedrine/moodle-qtype_ddmatch/pull/10
